// IanRobotiks — Expanded Parts Library
const PARTS = [
  { id:"arduino-uno", name:"Arduino Uno R3", category:"microcontroller", voltage:"5V", current:"50mA typ", weight:"25g", dimensions:"68.6×53.4mm", pins:"14 Digital, 6 PWM, 6 Analog",
    description:"The classic beginner microcontroller based on ATmega328P. Huge community and libraries.",
    useCases:"Education, prototyping, simple mobile robots, sensor hubs",
    compatible:["hc-sr04","sg90","l298n","mpu6050","9v-battery","tt-motor","ir-line"],
    pinout:"D0-D13, A0-A5, 5V, 3.3V, GND, VIN, RESET" },
  { id:"esp32", name:"ESP32 DevKit V1", category:"microcontroller", voltage:"3.3V", current:"80-240mA", weight:"10g", dimensions:"55×28mm", pins:"30+ GPIO + WiFi/BT",
    description:"Dual-core MCU with built-in WiFi and Bluetooth. Excellent for wireless robots.",
    useCases:"IoT robots, remote control, camera projects, mesh networks",
    compatible:["hc-sr04","sg90","mpu6050","lipo-2s","ssd1306","vl53l0x"],
    pinout:"GPIO0-39 (check silkscreen), 3.3V, GND, EN, BOOT" },
  { id:"rpi-zero", name:"Raspberry Pi Zero 2 W", category:"microcontroller", voltage:"5V", current:"150-300mA", weight:"9g", dimensions:"65×30mm", pins:"40-pin GPIO",
    description:"Tiny Linux computer with wireless. Best for vision and heavy software.",
    useCases:"Computer vision, ROS, complex autonomy, camera robots",
    compatible:["camera-module","lipo-2s","l298n","ssd1306"],
    pinout:"Standard 40-pin Raspberry Pi header" },
  { id:"arduino-nano", name:"Arduino Nano", category:"microcontroller", voltage:"5V", current:"40mA typ", weight:"7g", dimensions:"45×18mm", pins:"14 Digital, 6 Analog",
    description:"Compact version of the Uno. Perfect for tight robot chassis.",
    useCases:"Small robots, wearable robotics, space-constrained builds",
    compatible:["hc-sr04","sg90","l298n","mpu6050","9v-battery"],
    pinout:"D0-D13, A0-A7, 5V, 3.3V, GND, VIN, RST" },
  { id:"pico", name:"Raspberry Pi Pico", category:"microcontroller", voltage:"3.3V", current:"~20mA idle", weight:"3g", dimensions:"51×21mm", pins:"26 GPIO",
    description:"RP2040 dual-core microcontroller. Extremely cheap and capable.",
    useCases:"Cost-effective robots, custom PCBs, educational kits",
    compatible:["hc-sr04","sg90","mpu6050","ssd1306"],
    pinout:"GP0-GP28, 3.3V, GND, VBUS, VSYS" },
  { id:"sg90", name:"SG90 Micro Servo", category:"motor", voltage:"4.8–6V", current:"100-250mA", torque:"1.8 kg·cm", weight:"9g", dimensions:"22.5×12×28.5mm",
    description:"Tiny, lightweight servo ideal for arms, grippers and steering.",
    useCases:"Robot arms, pan-tilt camera, steering, grippers",
    compatible:["arduino-uno","esp32","arduino-nano","pico"],
    pinout:"Signal (PWM), VCC (5V), GND" },
  { id:"mg996r", name:"MG996R Servo", category:"motor", voltage:"4.8–7.2V", current:"500-900mA", torque:"10 kg·cm", weight:"55g", dimensions:"40.7×19.7×42.9mm",
    description:"High-torque metal-gear servo for stronger robot arms and mechanisms.",
    useCases:"Heavy robot arms, large pan-tilt, industrial prototypes",
    compatible:["arduino-uno","esp32","lipo-2s"],
    pinout:"Signal (PWM), VCC, GND" },
  { id:"tt-motor", name:"TT DC Gear Motor", category:"motor", voltage:"3–6V", current:"150-250mA", torque:"0.8–1.5 kg·cm", weight:"30g", dimensions:"~70×22×18mm",
    description:"Ubiquitous yellow plastic gearmotor used in countless hobby robots.",
    useCases:"Differential drive, line followers, simple mobile bases",
    compatible:["l298n","arduino-uno","9v-battery","chassis-2wd"],
    pinout:"Two wires (polarity = direction)" },
  { id:"n20-motor", name:"N20 Micro Gear Motor", category:"motor", voltage:"3–6V", current:"40-100mA", torque:"0.3–1.5 kg·cm", weight:"10g", dimensions:"~15×12×26mm + gearbox",
    description:"Tiny precision gearmotor, great for small robots and mechanisms.",
    useCases:"Micro robots, camera sliders, small arms",
    compatible:["l298n","arduino-nano","esp32","lipo-2s"],
    pinout:"Two wires" },
  { id:"nema17", name:"NEMA 17 Stepper", category:"motor", voltage:"12V typ", current:"1.5–2A", torque:"40–60 N·cm", weight:"280g", dimensions:"42×42×40mm",
    description:"Precise stepper motor widely used in 3D printers and CNC robots.",
    useCases:"Precise positioning, robotic arms, CNC, plotters",
    compatible:["a4988","arduino-uno","lipo-3s"],
    pinout:"4 or 6 wires (bipolar/unipolar)" },
  { id:"nema23", name:"NEMA 23 Stepper", category:"motor", voltage:"12–48V", current:"2–4A", torque:"1–3 N·m", weight:"600g+", dimensions:"57×57mm face",
    description:"Larger stepper for higher torque industrial-style robots.",
    useCases:"Large CNC, heavy robotic arms, automated platforms",
    compatible:["tb6600","arduino-uno"],
    pinout:"4 or 6 wires" },
  { id:"hc-sr04", name:"HC-SR04 Ultrasonic", category:"sensor", voltage:"5V", current:"15mA", range:"2–400cm", weight:"9g",
    description:"Classic ultrasonic distance sensor using sound pulses.",
    useCases:"Obstacle avoidance, parking, level sensing, mapping",
    compatible:["arduino-uno","esp32","arduino-nano","pico"],
    pinout:"VCC, Trig, Echo, GND" },
  { id:"vl53l0x", name:"VL53L0X ToF Laser", category:"sensor", voltage:"2.6–3.5V", current:"~20mA", range:"up to 2m", weight:"1g",
    description:"Time-of-Flight laser distance sensor. Much more precise than ultrasonic.",
    useCases:"Precise ranging, gesture detection, height sensing",
    compatible:["esp32","arduino-uno","pico"],
    pinout:"VIN, GND, SCL, SDA, GPIO1, XSHUT" },
  { id:"mpu6050", name:"MPU-6050 IMU", category:"sensor", voltage:"3.3–5V", current:"3.9mA", weight:"2g",
    description:"6-axis gyroscope + accelerometer. Essential for balance and orientation.",
    useCases:"Self-balancing robots, drones, motion tracking, AHRS",
    compatible:["arduino-uno","esp32","arduino-nano","pico"],
    pinout:"VCC, GND, SCL, SDA, XDA, XCL, AD0, INT" },
  { id:"mpu9250", name:"MPU-9250 9-DoF", category:"sensor", voltage:"3.3–5V", current:"~3.5mA", weight:"2g",
    description:"9-axis IMU (gyro + accel + magnetometer) for full orientation.",
    useCases:"Advanced orientation, compass, drones, VR tracking",
    compatible:["esp32","arduino-uno"],
    pinout:"VCC, GND, SCL, SDA, INT" },
  { id:"ir-line", name:"IR Line Sensor Array (5-ch)", category:"sensor", voltage:"3.3–5V", current:"20–40mA",
    description:"Array of infrared reflectance sensors for reliable line following.",
    useCases:"Line-following robots, edge detection, maze solvers",
    compatible:["arduino-uno","esp32","arduino-nano"],
    pinout:"VCC, GND, A0–A4 (or digital)" },
  { id:"pir", name:"HC-SR501 PIR Motion", category:"sensor", voltage:"5–20V", current:"~65µA idle",
    description:"Passive infrared motion detector for human presence.",
    useCases:"Security robots, interactive installations, wake-on-motion",
    compatible:["arduino-uno","esp32"],
    pinout:"VCC, OUT, GND" },
  { id:"dht22", name:"DHT22 Temp/Humidity", category:"sensor", voltage:"3.3–6V", current:"1.5mA max",
    description:"Digital temperature and humidity sensor.",
    useCases:"Environmental monitoring robots, weather stations",
    compatible:["arduino-uno","esp32","pico"],
    pinout:"VCC, Data, NC, GND" },
  { id:"camera-module", name:"Pi Camera Module v2", category:"sensor", voltage:"3.3V", current:"~250mA",
    description:"8MP camera for Raspberry Pi. Enables computer vision.",
    useCases:"Vision robots, object detection, surveillance, SLAM",
    compatible:["rpi-zero"],
    pinout:"CSI ribbon connector" },
  { id:"9v-battery", name:"9V Battery + Clip", category:"power", voltage:"9V", capacity:"~500mAh", weight:"45g",
    description:"Simple power source for low-current prototypes and testing.",
    useCases:"Small Arduino projects, quick tests",
    compatible:["arduino-uno","l298n","arduino-nano"],
    pinout:"+ and − terminals" },
  { id:"lipo-2s", name:"2S LiPo 7.4V 1000mAh", category:"power", voltage:"7.4V nom", capacity:"1000mAh", weight:"50g",
    description:"Rechargeable high-discharge pack for mobile robots.",
    useCases:"Mobile robots, drones, higher-power projects",
    compatible:["esp32","l298n","nema17","mg996r"],
    pinout:"Balance connector + main leads" },
  { id:"lipo-3s", name:"3S LiPo 11.1V 1500mAh", category:"power", voltage:"11.1V nom", capacity:"1500mAh", weight:"120g",
    description:"Higher voltage pack for steppers and stronger motors.",
    useCases:"Stepper robots, larger mobile platforms",
    compatible:["nema17","nema23","tb6600"],
    pinout:"Balance + main discharge" },
  { id:"18650-holder", name:"2×18650 Battery Holder", category:"power", voltage:"7.4V", capacity:"depends on cells", weight:"~30g empty",
    description:"Holder for two 18650 cells. Popular DIY power solution.",
    useCases:"Custom battery packs, portable robots",
    compatible:["esp32","l298n"],
    pinout:"+ and − leads" },
  { id:"buck-5v", name:"5V Buck Converter", category:"power", voltage:"In 7–24V → 5V out", current:"3A",
    description:"Step-down regulator to safely power 5V logic from higher batteries.",
    useCases:"Powering Arduino/sensors from LiPo",
    compatible:["arduino-uno","lipo-2s","lipo-3s"],
    pinout:"IN+, IN−, OUT+, OUT−" },
  { id:"l298n", name:"L298N Dual H-Bridge", category:"actuator", voltage:"5–35V motor / 5V logic", current:"2A per channel", weight:"30g",
    description:"Classic dual motor driver. Lets a MCU control direction and speed of two DC motors.",
    useCases:"Differential drive, dual motor platforms",
    compatible:["arduino-uno","tt-motor","n20-motor","9v-battery","lipo-2s"],
    pinout:"IN1–IN4, ENA, ENB, 5V, GND, Motor A/B, VCC" },
  { id:"a4988", name:"A4988 Stepper Driver", category:"actuator", voltage:"8–35V", current:"up to 2A",
    description:"Popular microstepping driver for NEMA 17 steppers.",
    useCases:"3D printers, CNC, precise robot joints",
    compatible:["nema17","arduino-uno"],
    pinout:"VMOT, GND, 1A/1B/2A/2B, DIR, STEP, ENABLE, MS1-3" },
  { id:"tb6600", name:"TB6600 Stepper Driver", category:"actuator", voltage:"9–42V", current:"up to 4A",
    description:"Higher-power stepper driver suitable for NEMA 23.",
    useCases:"Larger CNC and robotic systems",
    compatible:["nema23","arduino-uno"],
    pinout:"VCC, GND, PUL+, PUL−, DIR+, DIR−, ENA" },
  { id:"relay-module", name:"5V Relay Module", category:"actuator", voltage:"5V coil", current:"~70mA coil",
    description:"Electromechanical switch for high-voltage or high-current loads.",
    useCases:"Controlling pumps, lights, high-power devices from MCU",
    compatible:["arduino-uno","esp32"],
    pinout:"VCC, GND, IN, COM, NO, NC" },
  { id:"chassis-2wd", name:"2WD Robot Chassis Kit", category:"structural", material:"Acrylic/Plastic", weight:"~120g",
    description:"Basic two-wheel-drive chassis with motor mounts and caster.",
    useCases:"Line followers, obstacle avoiders, beginner platforms",
    compatible:["tt-motor","arduino-uno","hc-sr04","wheel-65mm"],
    pinout:"N/A (mechanical)" },
  { id:"chassis-4wd", name:"4WD Robot Chassis", category:"structural", material:"Acrylic/Aluminum", weight:"~250g",
    description:"Four-wheel-drive base for more traction and payload.",
    useCases:"Outdoor robots, heavier sensor payloads",
    compatible:["tt-motor","l298n","lipo-2s"],
    pinout:"N/A" },
  { id:"wheel-65mm", name:"65mm Rubber Wheel", category:"structural", dimensions:"65mm Ø", weight:"25g",
    description:"Common rubber wheel that fits TT motors.",
    useCases:"Mobile robot bases",
    compatible:["tt-motor","chassis-2wd"],
    pinout:"N/A" },
  { id:"omni-wheel", name:"Omni Wheel 48mm", category:"structural", dimensions:"48mm Ø", weight:"30g",
    description:"Omnidirectional wheel allowing sideways motion.",
    useCases:"Holonomic robots, mecanum-style platforms",
    compatible:["n20-motor","nema17"],
    pinout:"N/A" },
  { id:"servo-bracket", name:"Servo Bracket / Mount", category:"structural", material:"Aluminum/Plastic",
    description:"Mounting bracket for SG90 / MG996R servos.",
    useCases:"Robot arms, pan-tilt mechanisms",
    compatible:["sg90","mg996r"],
    pinout:"N/A" },
  { id:"breadboard", name:"Half-size Breadboard", category:"structural", dimensions:"82×55mm",
    description:"Solderless prototyping board for temporary circuits.",
    useCases:"Rapid electronics prototyping",
    compatible:["arduino-uno","esp32","arduino-nano"],
    pinout:"Power rails + terminal strips" },
  { id:"ssd1306", name:"SSD1306 OLED 0.96\"", category:"sensor", voltage:"3.3–5V", current:"~20mA",
    description:"Small monochrome OLED display for status and debugging.",
    useCases:"Robot status screens, debugging without serial",
    compatible:["arduino-uno","esp32","pico"],
    pinout:"VCC, GND, SCL, SDA" },
  { id:"ws2812b", name:"WS2812B LED Strip (8)", category:"actuator", voltage:"5V", current:"~60mA per LED",
    description:"Addressable RGB LEDs for status lighting and effects.",
    useCases:"Status indication, night robots, visual feedback",
    compatible:["arduino-uno","esp32"],
    pinout:"5V, GND, DIN" }
];

const CATEGORIES = {
  microcontroller: "Microcontroller",
  motor: "Motor",
  sensor: "Sensor",
  power: "Power",
  structural: "Structural",
  actuator: "Actuator / Driver"
};

const PRINTABLE_PARTS = [
  { id:"chassis-plate", name:"Chassis Base Plate", category:"structural", material:"PLA", layer:"0.2mm", infill:"20%", time:"~2h", notes:"Orient flat. No supports needed." },
  { id:"motor-mount", name:"TT Motor Mount", category:"structural", material:"PLA", layer:"0.2mm", infill:"30%", time:"~45min", notes:"Print with mounting face up." },
  { id:"wheel-hub", name:"Wheel Hub Adapter", category:"structural", material:"PLA", layer:"0.15mm", infill:"40%", time:"~30min", notes:"Higher infill for strength." },
  { id:"sensor-bracket", name:"Ultrasonic Bracket", category:"structural", material:"PLA", layer:"0.2mm", infill:"20%", time:"~25min", notes:"Fits HC-SR04 perfectly." },
  { id:"arm-link", name:"Servo Arm Link", category:"structural", material:"PLA", layer:"0.15mm", infill:"30%", time:"~40min", notes:"Use stronger filament for load-bearing." },
  { id:"battery-tray", name:"18650 Battery Tray", category:"structural", material:"PLA", layer:"0.2mm", infill:"25%", time:"~1h", notes:"Leave clearance for wires." },
  { id:"camera-mount", name:"Pi Camera Mount", category:"structural", material:"PLA", layer:"0.2mm", infill:"20%", time:"~35min", notes:"Adjustable angle version recommended." },
  { id:"gear-set", name:"Custom Gear Set (mod 1)", category:"structural", material:"PLA", layer:"0.15mm", infill:"50%", time:"~1.5h", notes:"Print slowly for tooth accuracy." }
];

const MODULES = [
  { id:"electronics", title:"Electronics Basics", desc:"Voltage, current, resistance, Ohm's law, series/parallel circuits",
    content:"Voltage is electrical potential difference. Current is the flow of charge. Resistance opposes current. Ohm's Law: V = I × R. Series circuits share current; parallel circuits share voltage. Master these before connecting any motor or sensor." },
  { id:"microcontrollers", title:"Microcontrollers & Programming", desc:"Arduino, ESP32, Pico, Raspberry Pi — C++ and Python",
    content:"A microcontroller is a computer on a chip. Arduino uses simplified C++. ESP32 adds WiFi/Bluetooth. Pico is cheap and dual-core. Raspberry Pi runs full Linux and is ideal for vision. Start with digitalWrite, analogRead, PWM (analogWrite), and Serial." },
  { id:"sensors", title:"Sensors & Actuators", desc:"Ultrasonic, ToF, IMU, IR, cameras and how to read them",
    content:"Sensors convert the physical world into electrical signals. Always match voltage levels (3.3V vs 5V). Use pull-ups for I²C. Calibrate. Popular libraries: NewPing, Wire, Adafruit_Sensor, VL53L0X." },
  { id:"motors", title:"Motors & Motion Control", desc:"DC, servo, stepper — speed, torque, control methods",
    content:"DC motors need an H-bridge for direction + PWM for speed. Servos have internal feedback and take a pulse width. Steppers move in precise steps and need drivers (A4988/TB6600). Choose based on torque, speed and precision needs." },
  { id:"power", title:"Power Systems & Batteries", desc:"Battery chemistry, capacity, regulators, safety",
    content:"LiPo packs offer high energy density but require proper charging and handling. Never exceed discharge ratings. Use a buck converter when feeding 5V/3.3V logic from a higher battery. Runtime ≈ Capacity (mAh) / Current (mA)." },
  { id:"mechanical", title:"Mechanical Design & 3D Printing", desc:"Chassis, gears, linkages, print settings",
    content:"Centre of mass, rigidity and weight distribution matter. 3D printing enables rapid iteration. Typical settings: 0.2 mm layer, 20–30% infill for structural parts. Orient to minimise supports and maximise strength along load paths." },
  { id:"control", title:"Control Systems & Feedback", desc:"Open vs closed loop, PID basics",
    content:"Open-loop systems command without measuring. Closed-loop systems use sensors to correct error. PID (Proportional-Integral-Derivative) is the workhorse controller for balancing and precise motion. Start with P, then carefully add I and D." },
  { id:"kinematics", title:"Basic Kinematics", desc:"Forward & inverse kinematics for arms and mobile robots",
    content:"Forward kinematics: joint angles → end-effector pose. Inverse kinematics: desired pose → joint angles. For differential drive, wheel speeds map to linear velocity v and angular velocity ω of the robot body." },
  { id:"ros", title:"Intro to ROS", desc:"Robot Operating System concepts",
    content:"ROS is middleware that lets robot software components talk via topics, services and actions. Use it when you need complex sensing, navigation or multiple processes. Nodes are the basic units of computation." },
  { id:"vision", title:"AI & Computer Vision", desc:"Cameras, OpenCV, simple object detection",
    content:"Cameras turn robots into perception systems. Start with colour thresholding and contours in OpenCV before neural nets. Always consider lighting, resolution and compute budget on embedded hardware." },
  { id:"safety", title:"Robotics Safety", desc:"Electrical, mechanical and operational safety",
    content:"Disconnect power when wiring. Use correct wire gauges. Keep fingers clear of moving parts and gears. LiPo batteries can fire if shorted or overcharged — use a fireproof bag for charging. Never leave a test robot unsupervised at full power." },
  { id:"project", title:"Your First Robot Project", desc:"Step-by-step: build a line-following robot",
    content:"1. Assemble 2WD chassis + TT motors + wheels. 2. Mount Arduino + L298N + IR array. 3. Wire power and signals carefully. 4. Write a simple proportional controller. 5. Tune speed and threshold on a real track. Celebrate the first successful lap." }
];

const GLOSSARY = [
  { term:"PWM", def:"Pulse Width Modulation — rapid on/off switching used to control motor speed and LED brightness." },
  { term:"H-Bridge", def:"Circuit that lets a microcontroller reverse the polarity of a DC motor (change direction)." },
  { term:"Torque", def:"Rotational force of a motor, measured in kg·cm or N·m." },
  { term:"GPIO", def:"General Purpose Input/Output pins configurable as digital inputs or outputs." },
  { term:"I²C", def:"Two-wire serial bus (SCL + SDA) used by many sensors (MPU-6050, OLED, etc.)." },
  { term:"SPI", def:"Faster serial protocol using separate clock, data and chip-select lines." },
  { term:"UART", def:"Hardware behind Serial communication (TX/RX)." },
  { term:"PID", def:"Proportional-Integral-Derivative controller — the most common feedback control algorithm in robotics." },
  { term:"LiPo", def:"Lithium Polymer battery — high energy density but requires careful handling and charging." },
  { term:"Differential Drive", def:"Mobile base with two independently driven wheels (plus usually a caster)." },
  { term:"Forward Kinematics", def:"Calculating end-effector position from joint angles." },
  { term:"Inverse Kinematics", def:"Calculating joint angles needed to reach a desired position." },
  { term:"ROS", def:"Robot Operating System — flexible framework for writing robot software." },
  { term:"ToF", def:"Time-of-Flight — distance measurement by timing a light pulse (e.g. VL53L0X)." },
  { term:"Microstepping", def:"Driving a stepper motor in fractions of a full step for smoother motion." },
  { term:"Watchdog", def:"Timer that resets the system if the main program hangs." },
  { term:"Brownout", def:"Voltage drop that causes a microcontroller to reset or behave unpredictably." },
  { term:"Dead Reckoning", def:"Estimating position by integrating velocity/heading without external references." }
];
